// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/core/prisma/schemas/schema.prisma',
  migrations: {
    path: 'src/corep/risma/migrations',
  },
  datasource: {
    url: process.env['SUPABASE_DATABASE_URL'],
  },
});
